### PR TITLE
Change Royalty patchop to MayRequire

### PR DESCRIPTION
**Pull request by zozilin**

### CODE REVIEW

**Comment by zozilin** [comment]
I actually don't know if it's better. I also didn't find a decisive argument one way or another. I just like that it looks neater.

**Comment by ItsSamGray** [comment]
I think we really might not want to do this replace patch, can cause too much headache in the long run with stuff changing and other mods patching pawn kinds as well. VAE already patches the Tribal Chief pawns which throws an error with CE loaded because of a conflict.

**Comment by albertbokor** [comment]
> I think we really might not want to do this replace patch, can cause too much headache in the long run with stuff changing and other mods patching pawn kinds as well. VAE already patches the Tribal Chief pawns which throws an error with CE loaded because of a conflict.

Troopers and Champions definitely need the buff.

**Comment by ItsSamGray** [comment]
Closing it until the major reword is done.

**Pull request closed without merging**
